manifest:
  remotes:
    - name: AtleMolholm
      url-base: https://github.com/AtleMolholm
  projects:
    - name: corne2
      remote: AtleMolholm
      revision: main
      import: app/west.yml
  self:
    path: config
